services:
  backend:
    image: backtest-buddy-backend:latest
    build:
      context: backend
      dockerfile: dev.Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - /__pycache__/
        - action: rebuild
          path: ./backend/requirements.txt

  frontend:
    image: backtest-buddy-frontend:latest
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
